title: Ashmita Nigam # your name (or website title) here
logo: "/images/Headshots_February-0052.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Summary:
  Analytical professional with expertise in customer-relationship management & client handling for 5 years providing decision-making insights for business.
  <br><br>
  <a href="https://www.linkedin.com/in/ashmitanigam/">View My LinkedIn Profile</a> 
  <a href="https://www.kaggle.com/ashmitan/">View My Kaggle Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
